name: Build Electron App

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Package Electron App
        run: npx electron-builder --win --x64

      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/*.exe
